### ISSUE TITLE
Standalone console tool gives error

### ISSUE THREAD

**Issue by hallba** [hallba/BioModelAnalyzer#59]
Current version of the console tool gives this F# error on running

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Main.main(String[] args)

**Comment by hallba** [comment]
Trying again with the latest windows release from github gives a different error. The code runs until Z3 is called

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Z3, Version=4.10.2.0, Culture=neutral, PublicKeyToken=9c8d792caae602a2' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Z.find_bifurcation(FSharpList`1 network, FSharpMap`2 range)
   at Counterexample.find_cex(FSharpList`1 net, FSharpMap`2 bounds, Boolean no_sat, concurrency concurrencyType)
   at Stabilize.stabilization_prover(FSharpList`1 model, Boolean no_sat, concurrency concurrencyType)
   at Main.runVMCAIEngine(FSharpList`1 qn, String proof_output, Boolean no_sat, concurrency concurrencyType)
   at Main.main$cont@375(FSharpRef`1 res, Unit unitVar)
   at Main.main(String[] args)

**Comment by hallba** [comment]
Failed to reproduce. Examination of my system revealed two installs. Complete uninstallation in add/remove and new installation fixed the issue
